require 'bundler'
Bundler.require

ActiveRecord::Base.establish_connection({
  adapter: 'postgresql',
  database: 'tictactoe_db'
  })

require 'sinatra/activerecord/rake'

namespace :db do
  desc "create tictactoe db"
  task :create_db_tictactoe do
    conn = PG::Connection.open()
    conn.exec('CREATE DATABASE tictactoe_db;')
    conn.close
  end

  desc "drop tictactoe db"
  task :drop_db_tictactoe do
    conn = PG::Connection.open()
    conn.exec('DROP DATABASE tictactoe_db;')
    conn.close
  end

end
