require 'bundler'
Bundler.require

ActiveRecord::Base.establish_connection({
  adapter: 'postgresql',
  database: 'hangman_db'
  })

require 'sinatra/activerecord/rake'

namespace :db do
  desc "create database hangman_db"
  task :create_hangman_db do
    conn = PG::Connection.open()
    conn.exec('CREATE DATABASE hangman_db;')
    conn.close
  end

  desc "drop database hangman_db"
  task :drop_hangman_db do
    conn = PG::Connection.open()
    conn.exec('DROP DATABASE hangman_db;')
    conn.close
  end
end
