require 'bundler'
Bundler.require

ActiveRecord::Base.establish_connection({
  adapter: 'postgresql',
  database: 'hangman_db'
  })

require 'sinatra/activerecord/rake'
require_relative 'models/word'

words = "Words.csv"

namespace :db do
  desc "create database hangman_db"
  task :create_hangman_db do
    conn = PG::Connection.open()
    conn.exec('CREATE DATABASE hangman_db;')
    conn.close
  end

  desc "drop database hangman_db"
  task :drop_hangman_db do
    conn = PG::Connection.open()
    conn.exec('DROP DATABASE hangman_db;')
    conn.close
  end

  desc "populate words"
  task :populate_words do
    CSV.foreach(words, headers: true) do |csv|
      name = csv[0]
      word = Word.new(name: name)
      word.url = "http://a-z-animals.com/animals/#{word.name.downcase.gsub(' ','-')}/"
      if word.url == "http://a-z-animals.com/animals/finnish-spitz/"
        word.url = "http://a-z-animals.com/animals/finnish-sptiz/"
      elsif word.url == "http://a-z-animals.com/animals/african-forest-elephant/"
        word.url = "http://a-z-animals.com/animals/african-elephant/"
      end
      word.save!
    end
  end

end
